BIST30 = [
    "THYAO.IS", "GARAN.IS", "ASELS.IS", "SISE.IS", "EREGL.IS",
    "KCHOL.IS", "TUPRS.IS", "BIMAS.IS", "AKBNK.IS", "SAHOL.IS",
    "PETKM.IS", "TOASO.IS", "FROTO.IS", "TCELL.IS", "YKBNK.IS",
    "EKGYO.IS", "HALKB.IS", "VAKBN.IS", "PGSUS.IS", "TAVHL.IS",
    "ARCLK.IS", "KORDS.IS", "MGROS.IS", "SASA.IS",
    "CCOLA.IS", "DOHOL.IS", "ENKAI.IS", "OTKAR.IS", "SOKM.IS"
]

PERIYOTLAR = {
    "4 Saatlik": "5d",
    "Gunluk": "3mo",
    "Haftalik": "1y"
}

BACKTEST_PERIYOT = "1y"

RSI_ASIRI_SATIM = 35
RSI_ASIRI_ALIM = 65
STOCH_ASIRI_SATIM = 25
STOCH_ASIRI_ALIM = 75
HACIM_CARPAN = 1.5
DESTEK_DIRENC_PENCERE = 20
